name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload production artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Change folder target to 'dist' if using Vite, or 'out' if Next.js export
        path: ./dist 